-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tgrmAlerter`.`users` 
DROP COLUMN `username`,
DROP COLUMN `used_id`,
ADD COLUMN `userid` VARCHAR(32) NOT NULL AFTER `phone`,
DROP INDEX `userid_UNIQUE` ,
ADD UNIQUE INDEX `userid_UNIQUE` (`userid` ASC),
DROP INDEX `used_id_UNIQUE` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

