-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tgrmAlerter`.`users` 
ADD COLUMN `userid` VARCHAR(32) NOT NULL AFTER `phone`,
ADD COLUMN `registered` TINYINT(1) NOT NULL AFTER `userid`,
ADD COLUMN `first_name` VARCHAR(24) NOT NULL AFTER `registered`,
ADD COLUMN `last_name` VARCHAR(32) NOT NULL AFTER `first_name`,
ADD COLUMN `registered_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `last_name`,
ADD UNIQUE INDEX `userid_UNIQUE` (`userid` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

