-- MySQL Script generated by MySQL Workbench
-- Сб 21 апр 2018 19:12:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mservice1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mservice1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mservice1` DEFAULT CHARACTER SET utf8 ;
USE `mservice1` ;

-- -----------------------------------------------------
-- Table `mservice1`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mservice1`.`test` ;

CREATE TABLE IF NOT EXISTS `mservice1`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(8) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
INSERT_METHOD = NO;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
