-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tgrmAlerter`.`users` 
DROP COLUMN `userid`,
ADD COLUMN `used_id` INT(10) UNSIGNED NOT NULL AFTER `phone`,
ADD COLUMN `username` VARCHAR(32) NOT NULL AFTER `used_id`,
DROP INDEX `userid_UNIQUE` ,
ADD UNIQUE INDEX `userid_UNIQUE` (`username` ASC),
ADD UNIQUE INDEX `used_id_UNIQUE` (`used_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

