
-- MySQL Script generated by MySQL Workbench
-- Сб 21 апр 2018 19:12:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mservice1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mservice1
-- -----------------------------------------------------
USE `mservice1` ;

-- -----------------------------------------------------
-- Table `mservice1`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mservice1`.`test` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
