-- MySQL Script generated by MySQL Workbench
-- Пт 27 апр 2018 02:58:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tgrmAlerter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tgrmAlerter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tgrmAlerter` DEFAULT CHARACTER SET utf8 ;
USE `tgrmAlerter` ;

-- -----------------------------------------------------
-- Table `tgrmAlerter`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgrmAlerter`.`users` ;

CREATE TABLE IF NOT EXISTS `tgrmAlerter`.`users` (
  `phone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`phone`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgrmAlerter`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgrmAlerter`.`requests` ;

CREATE TABLE IF NOT EXISTS `tgrmAlerter`.`requests` (
  `id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgrmAlerter`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgrmAlerter`.`errors` ;

CREATE TABLE IF NOT EXISTS `tgrmAlerter`.`errors` (
  `id` VARCHAR(36) NOT NULL,
  `request_id` VARCHAR(36) NOT NULL,
  `internal_code` TINYINT(1) UNSIGNED NOT NULL,
  `http_status` SMALLINT(2) UNSIGNED NOT NULL,
  `source` VARCHAR(18) NULL,
  `link` VARCHAR(32) NOT NULL,
  `displayed_title` VARCHAR(64) NOT NULL,
  `displayed_detail` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC),
  CONSTRAINT `fk_request_id`
    FOREIGN KEY (`request_id`)
    REFERENCES `tgrmAlerter`.`requests` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
