---
base:
  log_level: 'debug'
  http:
    listen: '167.114.232.119:8080' # IP:PORT
    host: 'beta.mh00.net:8080' # Hostname
    read_timeout: 500 # milliseconds
    write_timeout: 500 # milliseconds
  mysql:
    sql_debug: true
    host: '127.0.0.1:23306'
    username: 'mservice1'
    password: 'WmhnLWKxFZ3eTbDUkSVXXhNqyvJys4Vu'
    database: 'tgrmAlerter'
    migrations_path: 'extras/migrations'
  api:
    sign_secret: "VQJSBIOZrow8Tq5k7OAgytjqmNAckjaGpXk1rzmGRx3i3T4L7aInVNwQMN4k6l9u"
  telegram:
    botapi:
      tgrm_debug: false
      token: "440439991:AAFUPF_zCRJPL1sVlLCeF3YA1qnD6L8s60c"
      timeout: 5 # seconds
    queue:
      workers: 1
      worker_capacity: 1
      chain_buffer: 1
...
